# Generated by Django 2.0.4 on 2018-05-18 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CRM', '0022_auto_20180518_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('unscheduled', models.BooleanField(default=True)),
                ('time_slot', models.CharField(blank=True, choices=[('t0810', '8-10'), ('t0911', '9-11'), ('t1012', '10-12'), ('t1113', '11-1'), ('t1214', '12-2'), ('t1315', '1-3'), ('t1416', '2-4')], default='', max_length=20, null=True)),
                ('start', models.CharField(blank=True, max_length=30, null=True)),
                ('end', models.CharField(blank=True, max_length=30, null=True)),
                ('color', models.CharField(default='red', max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('appt', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.Customer')),
                ('jobsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.Jobsite')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.Ticket')),
            ],
        ),

    ]
