# Generated by Django 2.0.1 on 2018-01-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsite',
            name='slug',
            field=models.SlugField(default='4951 Wellington St'),
            preserve_default=False,
        ),
    ]
